apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-inner-chart
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: secrets-generator
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  Chart.yaml: |
    apiVersion: v2
    name: secret-values
    version: 0.1.0
    type: application
  secrets.yaml: |
    {{- $closeBraces := "}}" -}}
    {{- range .Values.secrets }}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ .secretName }}"
    type: Opaque
    data:
      {{- range $key, $value := .data }}
      {{- $trimmed := trim $value }}
      {{- if and (hasPrefix "{{" $trimmed) (hasSuffix "}}" $trimmed) }}
      {{ $key }}: {{ printf "%s | b64enc %s" (trimSuffix $closeBraces $trimmed) $closeBraces }}
      {{- else }}
      {{ $key }}: {{ $trimmed | b64enc }}
      {{- end }}
      {{- end }}
    {{- end }}
