apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-inner-chart
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: secrets-generator
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    #argocd.argoproj.io/sync-wave: "-1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  Chart.yaml: |
    apiVersion: v2
    name: secret-values
    version: 0.1.0
    type: application
  values.yaml: |
    secrets:
{{ .Values.secrets | toYaml | indent 6 }}
  secrets.yaml: |
    {{ "{{" }}- range .Values.secrets {{ "}}" }}
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{ "{{" }} .name | quote {{ "}}" }}
    type: Opaque
    data:
      {{ "{{" }}- range $key, $value := .data {{ "}}" }}
      {{ "{{" }} $key {{ "}}" }}: {{ "{{" }} tpl $value $ | b64enc {{ "}}" }}
      {{ "{{" }}- end {{ "}}" }}
    {{ "{{" }}- end {{ "}}" }}
