image:
  repository: alpine/k8s
  tag: "1.36.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  name: secrets-generator

# set to true if this is the only Helm Chart in the ArgoCD application.
# It creates a dummy configMap so that there is one resource to sync.
createDummyResource: false


secrets: []
#  - name: my-example-password
#    data:
#      password: "{{ randAlphaNum 32 }}"
#  - name: my-private-key
#    data:
#      SIGNING_KEY: |
#        {{ genPrivateKey "ecdsa" }}
